export const units = [
  {
    name: "Vargas",
    type: "Fire",
    rarity: 3,
    dps: 500,
    dpc: 500,
    clickRate: 1,
    description: "The Fire Hero of Grand Gaia.",
    icon: "https://static.wikia.nocookie.net/bravefrontierglobal/images/f/f6/Unit_ills_full_10017.png",
  },
  {
    name: "Selena",
    type: "Ice",
    rarity: 3,
    dps: 750,
    dpc: 250,
    clickRate: 1,
    description: "The Ice Hero of Grand Gaia.",
    icon: "https://static.wikia.nocookie.net/bravefrontierglobal/images/8/81/Unit_ills_full_20017.png",
  },
  {
    name: "Eze",
    type: "Thunder",
    rarity: 3,
    dps: 1000,
    dpc: 0,
    clickRate: 1,
    description: "The Thunder Hero of Grand Gaia.",
    icon: "https://static.wikia.nocookie.net/bravefrontierglobal/images/e/e6/Unit_ills_full_40017.png",
  },
  {
    name: "Lance",
    type: "Earth",
    rarity: 3,
    dps: 0,
    dpc: 1000,
    clickRate: 1,
    description: "The Earth Hero of Grand Gaia.",
    icon: "https://static.wikia.nocookie.net/bravefrontierglobal/images/8/82/Unit_ills_full_30017.png",
  },
  {
    name: "Atro",
    type: "Light",
    rarity: 3,
    dps: 400,
    dpc: 600,
    clickRate: 1,
    description: "The Light Hero of Grand Gaia.",
    icon: "https://static.wikia.nocookie.net/bravefrontierglobal/images/e/ef/Unit_ills_full_50017.png",
  },
  {
    name: "Magress",
    type: "Dark",
    rarity: 3,
    dps: 600,
    dpc: 400,
    clickRate: 1,
    description: "The Dark Hero of Grand Gaia.",
    icon: "https://static.wikia.nocookie.net/bravefrontierglobal/images/d/db/Unit_ills_full_60017.png",
  },
  {
    name: "Sefia",
    type: "Light",
    rarity: 4,
    dps: 5000,
    dpc: 5000,
    clickRate: 1,
    description: "The Light Angel with thousand swords",
    icon: "https://static.wikia.nocookie.net/bravefrontierglobal/images/b/bb/Unit_ills_full_50167.png",
  },
  {
    name: "Lunaris",
    type: "Dark",
    rarity: 4,
    dps: 10000,
    dpc: 0,
    clickRate: 1,
    description: "The dark witch of the 10 Gods guardians",
    icon: "https://static.wikia.nocookie.net/bravefrontierglobal/images/2/2a/Unit_ills_full_60317.png",
  },
  {
    name: "Kikuri",
    type: "Dark",
    rarity: 4,
    dps: 0,
    dpc: 10000,
    clickRate: 1,
    description: "The death angel known for her rivalry with Sefia.",
    icon: "https://static.wikia.nocookie.net/bravefrontierglobal/images/7/77/Unit_ills_full_60177.png",
  },
  {
    name: "Elza",
    type: "Dark",
    rarity: 4,
    dps: 10000,
    dpc: 0,
    clickRate: 1,
    description: "The beautifull chromatic reaper. So popular to be in different crossovers.",
    icon: "https://static.wikia.nocookie.net/bravefrontierglobal/images/0/09/Unit_ills_full_60527.png",
  },
  {
    name: "Serin",
    type: "Water",
    rarity: 4,
    dps: 5000,
    dpc: 5000,
    clickRate: 1,
    description: "One of the legendary Battle Maidens with the soul of a warrior.",
    icon: "https://static.wikia.nocookie.net/bravefrontierglobal/images/7/74/Unit_ills_full_820658.png",
  },
  {
    name: "Tilith",
    type: "Light",
    rarity: 5,
    dps: 10000,
    dpc: 10000,
    clickRate: 1,
    description: "The Opal goddess and also your guide.",
    icon: "https://static.wikia.nocookie.net/bravefrontierglobal/images/3/3d/Unit_ills_full_850808.png",
  },
  {
    name: "Karl",
    type: "Water",
    rarity: 5,
    dps: 5000,
    dpc: 15000,
    clickRate: 1,
    description: "The legendary summoner's childhood friend",
    icon: "https://static.wikia.nocookie.net/bravefrontierglobal/images/6/68/Unit_ills_full_820808.png",
  },
  {
    name: "Seria",
    type: "Fire",
    rarity: 5,
    dps: 15000,
    dpc: 5000,
    clickRate: 1,
    description: "One of the best summoner and friend of the legendary summoner",
    icon: "https://static.wikia.nocookie.net/bravefrontierglobal/images/8/8c/Unit_ills_full_810808.png",
  },
  {
    name: "Lugina",
    type: "Earth",
    rarity: 5,
    dps: 0,
    dpc: 20000,
    clickRate: 1,
    description: "The Arrogant Emerald Summoner, but a reliable allie and friend.",
    icon: "https://static.wikia.nocookie.net/bravefrontierglobal/images/9/92/Unit_ills_full_830808.png",
  },
  {
    name: "Paris",
    type: "Thunder",
    rarity: 5,
    dps: 20000,
    dpc: 0,
    clickRate: 1,
    description: "The lovely lady from the governement. Friend of the legendary Summoner",
    icon: "https://static.wikia.nocookie.net/bravefrontierglobal/images/3/34/Unit_ills_full_840808.png",
  },
  {
    name: "Luc Damas",
    type: "Light",
    rarity: 6,
    dps: 10000000,
    dpc: 10000000,
    clickRate: 1,
    description:
      "The Ultimate Professor. His skills are unmatched to this day.",
    icon: "https://pbs.twimg.com/profile_images/1423200562523344905/75gd-ijW_400x400.jpg",
  },
];
